package gpt

import (
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/monopolly/file"
	"github.com/monopolly/images"
)

func NewImageReq(name ...string) (res *ImageReq) {
	res = new(ImageReq)
	res.created = time.Now().Unix()
	if name != nil {
		res.name = strings.Join(name, "_")
	}
	res.retry = 3
	return
}

type ImageReq struct {
	chat    string //chat id
	created int64
	name    string
	promt   []string
	system  []string

	provider    Provider
	model       *Model
	temperature float64
	images      []*images.Image //base64 or links
	retry       int
	timeout     time.Duration

	price   float64
	summary Summary

	// The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only
	// `n=1` is supported.
	count int
	// The compression level (0-100%) for the generated images. This parameter is only
	// supported for the GPT image models with the `webp` or `jpeg` output formats, and
	// defaults to 100.
	compression int
	// A unique identifier representing your end-user, which can help OpenAI to monitor
	// and detect abuse.
	// [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).
	uid string
	// backgrounds. Must be one of `transparent`, `opaque`, or `auto` (default value).
	// When `auto` is used, the model will automatically determine the best background
	// for the image.
	//
	// `gpt-image-2` and `gpt-image-2-2026-04-21` do not support transparent
	// backgrounds. Requests with `background` set to `transparent` will return an
	// error for these models; use `opaque` or `auto` instead.
	//
	// If `transparent`, the output format needs to support transparency, so it should
	// be set to either `png` (default value) or `webp`.
	//
	// Any of "transparent", "opaque", "auto".
	background string
	// Control the content-moderation level for images generated by the GPT image
	// models. Must be either `low` for less restrictive filtering or `auto` (default
	// value).
	//
	// Any of "low", "auto".
	moderation string
	// The format in which the generated images are returned. This parameter is only
	// supported for the GPT image models. Must be one of `png`, `jpeg`, or `webp`.
	//
	// Any of "png", "jpeg", "webp".
	format string
	// The quality of the image that will be generated.
	//
	//   - `auto` (default value) will automatically select the best quality for the
	//     given model.
	//   - `high`, `medium` and `low` are supported for the GPT image models.
	//   - `hd` and `standard` are supported for `dall-e-3`.
	//   - `standard` is the only option for `dall-e-2`.
	//
	// Any of "standard", "hd", "low", "medium", "high", "auto".
	quality string
	// The format in which generated images with `dall-e-2` and `dall-e-3` are
	// returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes
	// after the image has been generated. This parameter isn't supported for the GPT
	// image models, which always return base64-encoded images.
	//
	// Any of "url", "b64_json".
	link bool
	// The size of the generated images. For `gpt-image-2` and
	// `gpt-image-2-2026-04-21`, arbitrary resolutions are supported as `WIDTHxHEIGHT`
	// strings, for example `1536x864`. Width and height must both be divisible by 16
	// and the requested aspect ratio must be between 1:3 and 3:1. Resolutions above
	// `2560x1440` are experimental, and the maximum supported resolution is
	// `3840x2160`. The requested size must also satisfy the model's current pixel and
	// edge limits. The standard sizes `1024x1024`, `1536x1024`, and `1024x1536` are
	// supported by the GPT image models; `auto` is supported for models that allow
	// automatic sizing. For `dall-e-2`, use one of `256x256`, `512x512`, or
	// `1024x1024`. For `dall-e-3`, use one of `1024x1024`, `1792x1024`, or
	// `1024x1792`.
	size string
	// The style of the generated images. This parameter is only supported for
	// `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean
	// towards generating hyper-real and dramatic images. Natural causes the model to
	// produce more natural, less hyper-real looking images.
	//
	// Any of "vivid", "natural".
	style string
}

type ImageResp struct {
	ChatID  string   `json:"chat_id,omitempty"`
	Images  [][]byte `json:"images,omitempty"`
	URLs    []string `json:"urls,omitempty"`
	Summary *Summary `json:"summary,omitempty"`
	Raw     any      `json:"-"`
}

func (a *ImageReq) AddImageLocalFile(path string) (m *ImageReq) {
	body := file.OpenE(path)
	if body == nil {
		return
	}

	a.AddImage(body)
	return
}

// conversation id (chatgpt)
func (a *ImageReq) SetChatID(v string) (m *ImageReq) {
	a.chat = v
	return a
}

// conversation id (chatgpt)
func (a *ImageReq) ChatID() (id string) {
	return a.chat
}

func (a *ImageReq) Model(v ...*Model) *Model {
	switch v {
	case nil:
		return a.model
	default:
		a.model = v[0]
		return nil
	}
}

func (a *ImageReq) Count(v int) (m *ImageReq) {
	a.count = v
	return a
}

func (a *ImageReq) Compression(v int) (m *ImageReq) {
	a.compression = v
	return a
}

func (a *ImageReq) CompressionLow() (m *ImageReq) {
	a.compression = 30
	return a
}

func (a *ImageReq) CompressionMedium() (m *ImageReq) {
	a.compression = 70
	return a
}

func (a *ImageReq) CompressionHigh() (m *ImageReq) {
	a.compression = 100
	return a
}

func (a *ImageReq) User(v string) (m *ImageReq) {
	a.uid = v
	return a
}

func (a *ImageReq) Background(v string) (m *ImageReq) {
	a.background = v
	return a
}

func (a *ImageReq) Transparent() (m *ImageReq) {
	a.background = "transparent"
	return a
}

func (a *ImageReq) Opaque() (m *ImageReq) {
	a.background = "opaque"
	return a
}

func (a *ImageReq) BackgroundAuto() (m *ImageReq) {
	a.background = "auto"
	return a
}

func (a *ImageReq) Moderation(v string) (m *ImageReq) {
	a.moderation = v
	return a
}

func (a *ImageReq) ModerationLow() (m *ImageReq) {
	a.moderation = "low"
	return a
}

func (a *ImageReq) ModerationAuto() (m *ImageReq) {
	a.moderation = "auto"
	return a
}

func (a *ImageReq) Format(v string) (m *ImageReq) {
	a.format = v
	return a
}

func (a *ImageReq) PNG() (m *ImageReq) {
	a.format = "png"
	return a
}

func (a *ImageReq) JPG() (m *ImageReq) {
	a.format = "jpeg"
	return a
}

func (a *ImageReq) JPEG() (m *ImageReq) {
	a.format = "jpeg"
	return a
}

func (a *ImageReq) WebP() (m *ImageReq) {
	a.format = "webp"
	return a
}

func (a *ImageReq) Link() (m *ImageReq) {
	a.link = true
	return a
}

func (a *ImageReq) Quality(v string) (m *ImageReq) {
	a.quality = v
	return a
}

func (a *ImageReq) QualityAuto() (m *ImageReq) {
	a.quality = "auto"
	return a
}

func (a *ImageReq) QualityLow() (m *ImageReq) {
	a.quality = "low"
	return a
}

func (a *ImageReq) QualityMedium() (m *ImageReq) {
	a.quality = "medium"
	return a
}

func (a *ImageReq) QualityHigh() (m *ImageReq) {
	a.quality = "high"
	return a
}

func (a *ImageReq) QualityHD() (m *ImageReq) {
	a.quality = "hd"
	return a
}

func (a *ImageReq) QualityStandard() (m *ImageReq) {
	a.quality = "standard"
	return a
}

func (a *ImageReq) Size(v string) (m *ImageReq) {
	a.size = v
	return a
}

func (a *ImageReq) SizeAuto() (m *ImageReq) {
	a.size = "auto"
	return a
}

func (a *ImageReq) Size256() (m *ImageReq) {
	a.size = "256x256"
	return a
}

func (a *ImageReq) Size512() (m *ImageReq) {
	a.size = "512x512"
	return a
}

func (a *ImageReq) Size1024() (m *ImageReq) {
	a.size = "1024x1024"
	return a
}

func (a *ImageReq) SizeLandscape() (m *ImageReq) {
	a.size = "1536x1024"
	return a
}

func (a *ImageReq) SizePortrait() (m *ImageReq) {
	a.size = "1024x1536"
	return a
}

func (a *ImageReq) SizeWide() (m *ImageReq) {
	a.size = "1792x1024"
	return a
}

func (a *ImageReq) SizeTall() (m *ImageReq) {
	a.size = "1024x1792"
	return a
}

func (a *ImageReq) Style(v string) (m *ImageReq) {
	a.style = v
	return a
}

func (a *ImageReq) StyleVivid() (m *ImageReq) {
	a.style = "vivid"
	return a
}

func (a *ImageReq) StyleNatural() (m *ImageReq) {
	a.style = "natural"
	return a
}

// url, body, base64, dataurl
func (a *ImageReq) AddImage(v any) (m *ImageReq) {

	switch body := v.(type) {
	case *images.Image:
		a.images = append(a.images, body)
	case []byte:
		img, err := images.New(body)
		if err != nil {
			log.Println("gpt image format error")
			return
		}
		a.images = append(a.images, img)
	case string:
		switch {
		case strings.Contains(body, "http"):
			temp := file.Download(body)
			if temp == nil {
				log.Println("gpt download image error")
				return
			}
			img, err := images.New(temp)
			if err != nil {
				log.Println("gpt image format error")
				return
			}
			a.images = append(a.images, img)
		default:
			switch {
			case images.IsBase64ImageDataURL(body):
				img, err := images.New([]byte(body))
				if err != nil {
					log.Println("gpt image format error")
					return
				}
				a.images = append(a.images, img)
			case images.IsBase64(body):
				body = images.CleanBase64(body)
				img, err := images.New([]byte(body))
				if err != nil {
					log.Println("gpt image format error")
					return
				}
				a.images = append(a.images, img)
			}

		}
	}

	return a
}

// max retry attemts
func (a *ImageReq) Retry(max int) (m *ImageReq) {
	a.retry = max
	return a
}

// max retry attemts
func (a *ImageReq) Timeout(t time.Duration) (m *ImageReq) {
	a.timeout = t
	return a
}

// add promt
func (a *ImageReq) Promt(lines ...string) (m *ImageReq) {
	a.promt = append(a.promt, lines...)
	return a
}

// empty line
func (a *ImageReq) Line() (m *ImageReq) {
	a.promt = append(a.promt, "")
	return a
}

// add promtf
func (a *ImageReq) Promtf(k string, v ...any) (m *ImageReq) {
	a.promt = append(a.promt, fmt.Sprintf(k, v...))
	return a
}

// add system promt
func (a *ImageReq) SystemPromt(lines ...string) (m *ImageReq) {
	a.system = append(a.system, lines...)
	return a
}

// add system promtf
func (a *ImageReq) SystemPromtf(k string, v ...any) (m *ImageReq) {
	a.system = append(a.system, fmt.Sprintf(k, v...))
	return a
}

// render promt
func (a *ImageReq) RenderPromt() string {
	return CompactText(strings.Join(a.promt, "\n"))
}

// render system promt
func (a *ImageReq) RenderSystemPromt() string {
	return CompactText(strings.Join(a.system, "\n"))
}

// Deepseek: 0 math, 1 analys, 1.3 chat/translation, 1.5 creative
func (a *ImageReq) Temperature(t float64) (m *ImageReq) {
	a.temperature = t
	return a
}

func (a *ImageReq) Summary() (res *Summary) {
	return &a.summary
}

func (a *ImageReq) imagesSize() (bytes int) {
	for _, x := range a.images {
		bytes += x.Size
	}
	return
}
